PROJECT M.A.P/Project/Project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from user import views as user_views

from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name = 'user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'user/logout.html'), name='logout'), #class based views
    path('', include('map.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PROJECT M.A.P/Project/map/urls.py
from django.urls import path, register_converter

from . import views
from .views import (
	ExamListView,
	ExamDetailView,
	ExamCreateView,
    ExamFormView,
)

app_name='map'
urlpatterns = [
    path("", ExamListView.as_view(), name='map-home'),
    path("exam/form/", ExamFormView.as_view(), name="exam-form"),
    path("exam/new/", ExamCreateView.as_view(), name="exam-create"),
    path("exam/<str:pk>/", ExamDetailView.as_view(), name="exam-detail"),
    path("login_student/", views.login_student, name='map-login'),
    path("register_student", views.register_student, name='map-register'),
    path('add_student/', views.add_student, name='add_student'),
    path('front/', views.front, name="front"),
    path('results/', views.display_results, name="show-results"),
]

PROJECT M.A.P/Project/map/models.py
from django.db import models
from neomodel import StructuredNode
from neomodel import StringProperty
from django_neomodel import DjangoNode
from django.shortcuts import reverse

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User



class Student(DjangoNode):
	# MALE = 'M'
	# FEMALE = 'F'
	# GENDER = [
	#     (MALE, 'Male'),
	#     (FEMALE, 'Female')

	# ]
	name = StringProperty(required = True, max_length = 50)
	roll = StringProperty(unique_index = True, required = True, max_length = 10)
	# gender = models.CharField(max_length = 2, choices = GENDER)
	#marks = {}

	def __init__(self, name, roll):
		self.name = name
		self.roll = roll

	def __str__(self):
		return self.name


class Teacher(DjangoNode):
	name = StringProperty(required = True, max_length = 50)
	#password = null

	def __init__(self, name):
		self.name = name

	def __str__(self):
		return self.name

def validate_subject(value):
	if not value.isalnum():
		raise ValidationError(_('%(value)s is not valid. Please use alphanumneric characters as subject names'), params={'value': value},)



class Exam(models.Model):  #Exam can have many questions
	subject = models.CharField(primary_key=True, unique = True, validators = [validate_subject], max_length = 20)  #make to reject a string of length 0
	#subject = models.TextField(unique = True)
	set_by = models.ForeignKey(User, on_delete = models.DO_NOTHING)
	#start = 
	#end =  
	#duration = 
	# def __init__(self, name):  'Question' object has no attribute '_state'
	# 	self.subject = name

	def __str__(self):
		return self.subject

	# def get_absolute_url(self):
	# 	return "/exam-detail/%s/" % self.pk


class Question(models.Model):
	exam = models.ForeignKey(Exam, on_delete = models.CASCADE) #deleting an exam deletes all questions
	question = models.TextField(unique = True)
	#skill = models.TextField()
	#answer = models.TextField()		#self.answer = answer

	def __str__(self):
		return self.question
		

class Option(models.Model):
	question = models.ForeignKey(Question, on_delete = models.CASCADE) #deleting a question deletes the correspondent options #handle Integrity Error
	option = models.TextField()
	answer = models.BooleanField(default = False)

	def __str__(self):
		return self.option

PROJECT M.A.P/Project/map/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse

from . models import Student, Exam
from django.views.generic import (
	ListView,
	DetailView,
	CreateView,
	FormView,
)

def home(request):
	context = {
	    'exams': Exam.objects.all()
	}
	return render(request, 'map/home.html', context)

class ExamListView(ListView): #class based views
 	model = Exam
 	template_name = 'map/home.html'  #<app>/<model>_<viewtype>.html
 	context_object_name = 'exams'
 	ordering = ['subject'] #['-exam']


class ExamDetailView(DetailView):
 	model = Exam


class ExamCreateView(CreateView):
	model = Exam
	#template_name = 'map/exam_form.html'
	fields = ['subject']

class ExamFormView(FormView):
	model = Exam 



def login_student(request):
	return render(request, 'map/login.html')

def register_student(request):
	context = {"title": 'Register'}
	return render(request, 'map/register.html', context)

def add_student(request):
	name = request.POST['name']
	roll = request.POST['roll']
	try:
		student = Student.nodes.get(roll = roll, name = name)
	except:
		Student(roll = roll, name = name).save()
	else:
		return HttpResponse("You are already registered. Please Login")
	return HttpResponse("You're successfully registered")
	#return HttpResponseRedirect(reverse("You are registered"))

def front(request):
	return render(request, 'map/front.html')

def display_results(request):
	pass

# def add_question(request):
# 	subject = request.POST["subject"]
# 	question = request.POST["question"]
# 	op1 = request.POST["op1"]
# 	op2 = request.POST["op1"]
# 	op3 = request.POST["op1"]
# 	op4 = request.POST["op1"]
# 	exam = Exam(subject= subject)
	

PROJECT M.A.P/Project/map/templates/map/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	 <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


    
<link rel="stylesheet" type="text/css" href="{% static 'map/main.css' %}">

	{% if title %}
		<title>{{ title }}</title>
	{% else %}
		<title> MAP PAGE </title>
	{% endif %}	
</head>
<body>
		<header class="site-header">
	  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
	    <div class="container">
	      <a class="navbar-brand mr-4" href="/">Project M.A.P</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	      </button>
	      <div class="collapse navbar-collapse" id="navbarToggle">
	        <div class="navbar-nav mr-auto">
	          <a class="nav-item nav-link" href="{% url 'map:map-home' %}">Home</a>  <!-- no hardcoded links -->
	          <a class="nav-item nav-link" href="{% url 'map:map-home' %}">About</a>
	        </div>
	        <!-- Navbar Right Side -->
	        <div class="navbar-nav">
              {% if user.is_authenticated %}
                  <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                  <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
              {% else %}
	          <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
	          <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
              <a class="nav-item nav-link" href="{% url 'map:map-register' %}">Student</a>
              {% endif %}
	        </div>
	      </div>
	    </div>
	  </nav>
	</header>
	<main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
        	{% if messages %}
        	    {% for message in messages %}
        	        <div class="alert alert-{{ message.tags }}">
        	            {{ message }}
        	        </div>
        	    {% endfor %}
        	{% endif %}
          {% block content %}{% endblock %}
        	
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

	
	 <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
 
</body>
</html>

PROJECT M.A.P/Project/map/templates/map/exam_detail.html
{% extends "map/base.html" %}
{% block content %}
<form action = "{% url 'map:show-results' %}" method=POST>
    {% csrf_token %}
     <div style="background-color:lightgreen">
        <h1>CHOOSE THE CORRECT ANSWER</h1>
    </div>
    {% for question in object.question_set.all %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    Q{{ forloop.counter }} &emsp; {{ question }}
                    {% comment %}
                    <!-- <small class="text-muted">{{ exam.start_date|date:"F d, Y"}}</small> -->
                    {% endcomment %}
                </div>
                {% for option in question.option_set.all %}
                     <input type="radio" id="{{ option.id }}" name="{{ question }}" value="{{ option }}">
                     <label for="{{ option.id }}" > {{ option }} </label> <br>
                {% endfor %}
                {% comment %}
                <!-- <h2><a class="article-title" href="#">{{ exam.start }}</a></h2>
                <p class="article-content"> {{ exam.description }} </p> -->
                {% endcomment %}
            </div>
        </article>
    {% endfor %}
{% endblock content %}
</form>

PROJECT M.A.P/Project/map/templates/map/exam_form.html
{% extends "map/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    	<form method = "POST">
    		{% csrf_token %}
    		<fieldset class ="form-group">
    			<legend class="border-bottom mb-4">
                    New Exam
    			</legend>
    			{{ form|crispy }}
    		</fieldset>
    		<div class="form-group">
    			<button class="btn btn-outline-info" type="submit">Create</button>
    		</div>
    	</form>
    </div>
{% endblock content %}

PROJECT M.A.P/Project/map/templates/map/front.html
<!DOCTYPE html>
<html>
<body>




<form action="project.html">

 <center><input type="image" src="exam.jpg" alt="Submit" width="500" height="500"></center>
</form>



</body>
</html>

PROJECT M.A.P/Project/map/templates/map/home.html
{% extends "map/base.html" %}
{% block content %}
    <p>WELCOME HOME</p>
    {% for exam in exams %}
        <article class="media content-section">
        	<div class="media-body">
        		<div class="article-metadata">
        			<a class="mr-2" href="{% url 'map:exam-detail' exam.pk %}">{{ exam }} </a>
        			{% comment %}
        			<!-- <small class="text-muted">{{ exam.start_date|date:"F d, Y"}}</small> -->
        			{% endcomment %}
                    <small class="text-muted">{{ exam.set_by }}</small>
        		</div>
        		{% comment %}
        		<!-- <h2><a class="article-title" href="#">{{ exam.start }}</a></h2>
        		<p class="article-content"> {{ exam.description }} </p> -->
        		{% endcomment %}
        	</div>
        </article>
    {% endfor %}
{% endblock content %}

PROJECT M.A.P/Project/map/templates/map/login.html
<html>
<style>
body{
  background-image:url(pic.jpg);
  background-size:200px 112.5px;
}
input[type=text], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  width: 100%;
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=number] {
  width: 100%;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

div {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}
</style>
<body>



<div>
  <h1>Examination</h1>
  <form action="{% url 'map:add_student'  %}" method="POST">
    {%  csrf_token %}
    <label for="fname">Full Name:</label>
    <input type="text" id="fname" name="name" placeholder="Enter your name along with surname">

    <label for="Roll no">Roll no:</label>
    <input type="text" id="Roll no" name="roll" placeholder="Enter your Roll no" >


  
    <input type="submit" value="Submit">
  </form>
</div>

</body>
</html>
<!-- 
  <form action="" method="POST">  //pending
    <table align="center">
      <tr>
        <td>Name :</td>
        <td><input type="text" name="name" required></td>
      </tr>
      <tr>
        <td>Roll :</td>
        <td><input type="text" name="roll" required></td>
      </tr>
      <tr>
      </tr>
      <tr>
        <td><input type="submit" value="Submit"></td>
      </tr>
    </table>
  </form>
 -->

PROJECT M.A.P/Project/map/templates/map/maths_paper.html
<!DOCTYPE html>
<html>
<style>
input[type=submit] {
  width: 100%;
  background-color: #1E90FF;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}
</style>
<body backgroung-im>
<div style="background-color:lightgreen">
<h1>CHOOSE THE CORRECT ANSWER</h1>
</div>

<form action="/action_page.php">
<div style="background-color:lightblue">
  <p>q1:33+23?</p><!--answer b -->

  <input type="radio" id="q1a" name="q1" value="a">
  <label for="q1a">46</label><br>
  <input type="radio" id="q1b" name="q1" value="b">
  <label for="q1b">56</label><br>
  <input type="radio" id="q1c" name="q1" value="c">
  <label for="q1c">59</label><br>
  <input type="radio" id="q1d" name="q1" value="d">
  <label for="q1d">66</label></br>
</div>

<div style="background-color:lightgreen">
  <p>q2:33-13?</p><!--answer b -->

  <input type="radio" id="q2a" name="q2" value="a">
  <label for="q2a">10</label><br>
  <input type="radio" id="q2b" name="q2" value="b">
  <label for="q2b">20</label><br>
  <input type="radio" id="q2c" name="q2" value="c">
  <label for="q2c">30</label><br>
  <input type="radio" id="q2d" name="q2" value="d">
  <label for="q2d">40</label><br>
</div>

<div style="background-color:lightblue">
  <p>q3:16/4?</p><!--answer c -->

  <input type="radio" id="q3a" name="q3" value="a">
  <label for="q3a">3</label><br>
  <input type="radio" id="q3b" name="q3" value="b">
  <label for="q3b">5</label><br>
  <input type="radio" id="q3c" name="q3" value="c">
  <label for="q3c">4</label><br>
  <input type="radio" id="q3d" name="q3" value="d">
  <label for="q3d">2</label><br>
</div>

<div style="background-color:lightgreen">
  
  <p>q4:9X6?</p><!--answer d -->

  <input type="radio" id="q4a" name="q4" value="a">
  <label for="q4a">44</label><br>
  <input type="radio" id="q4b" name="q4" value="b">
  <label for="q4b">55</label><br>
  <input type="radio" id="q4c" name="q4" value="c">
  <label for="q4c">45</label><br>
  <input type="radio" id="q4d" name="q4" value="d">
  <label for="q4d">54</label><br>
</div>

<div style="background-color:lightblue">  
  <p>q5:75+16?</p><!--answer a -->

  <input type="radio" id="q5a" name="q5" value="a">
  <label for="q5a">91</label><br>
  <input type="radio" id="q5b" name="q5" value="b">
  <label for="q5b">101</label><br>
  <input type="radio" id="q5c" name="q5" value="c">
  <label for="q5c">81</label><br>
  <input type="radio" id="q5d" name="q5" value="d">
  <label for="q5d">111</label><br>
</div>

<div style="background-color:lightgreen">
  <p>q6:44-9?</p><!--answer b -->

  <input type="radio" id="q6a" name="q6" value="a">
  <label for="q6a">34</label><br>
  <input type="radio" id="q6b" name="q6" value="b">
  <label for="q6b">35</label><br>
  <input type="radio" id="q6c" name="q6" value="c">
  <label for="q6c">36</label><br>
  <input type="radio" id="q6d" name="q6" value="d">
  <label for="q6d">37</label><br>
</div>

<div style="background-color:lightblue">
  <p>q7:21/3?</p><!--answer a -->

  <input type="radio" id="q7a" name="q7" value="a">
  <label for="q7a">7</label><br>
  <input type="radio" id="q7b" name="q7" value="b">
  <label for="q7b">8</label><br>
  <input type="radio" id="q7c" name="q7" value="c">
  <label for="q7c">6</label><br>
  <input type="radio" id="q7d" name="q7" value="d">
  <label for="q7d">5</label><br>
</div>

<div style="background-color:lightgreen">
  <p>q8:8X7?</p><!--answer b -->

  <input type="radio" id="q7a" name="q8" value="a">
  <label for="q8a">46</label><br>
  <input type="radio" id="q7b" name="q8" value="b">
  <label for="q8b">56</label><br>
  <input type="radio" id="q7c" name="q8" value="c">
  <label for="q8c">49</label><br>
  <input type="radio" id="q7d" name="q8" value="d">
  <label for="q8d">63</label><br>
</div>

<div style="background-color:lightblue">
  <p>q9:18+54?</p><!--answer b -->

  <input type="radio" id="q9a" name="q9" value="a">
  <label for="q9a">62</label><br>
  <input type="radio" id="q9b" name="q9" value="b">
  <label for="q9b">72</label><br>
  <input type="radio" id="q9c" name="q9" value="c">
  <label for="q9c">83</label><br>
  <input type="radio" id="q9d" name="q9" value="d">
  <label for="q9d">73</label><br>
</div>

<div style="background-color:lightgreen">
  <p>q10:35-15?</p><!--answer c -->

  <input type="radio" id="q10a" name="q10" value="a">
  <label for="q10a">25</label><br>
  <input type="radio" id="q10b" name="q10" value="b">
  <label for="q10b">15</label><br>
  <input type="radio" id="q10c" name="q10" value="c">
  <label for="q10c">20</label><br>
  <input type="radio" id="q10d" name="q10" value="d">
  <label for="q10d">10</label><br>
</div>

<div style="background-color:lightblue">  
  <p>q11:28/4?</p><!--answer c -->

  <input type="radio" id="q11a" name="q11" value="a">
  <label for="q9a">5</label><br>
  <input type="radio" id="q11b" name="q11" value="b">
  <label for="q11b">6</label><br>
  <input type="radio" id="q11c" name="q11" value="c">
  <label for="q11c">7</label><br>
  <input type="radio" id="q11d" name="q11" value="d">
  <label for="q11d">8</label><br>
</div>

<div style="background-color:lightgreen">
  <p>q12:6X6?</p><!--answer b -->

  <input type="radio" id="q12a" name="q12" value="a">
  <label for="q12a">26</label><br>
  <input type="radio" id="q12b" name="q12" value="b">
  <label for="q12b">36</label><br>
  <input type="radio" id="q12c" name="q12" value="c">
  <label for="q12c">46</label><br>
  <input type="radio" id="q12d" name="q12" value="d">
  <label for="q12d">56</label><br>
</div>

<div style="background-color:lightblue"> 
 <p>q13:74+12?</p><!--answer a -->

  <input type="radio" id="q13a" name="q13" value="a">
  <label for="q13a">96</label><br>
  <input type="radio" id="q13b" name="q13" value="b">
  <label for="q13b">86</label><br>
  <input type="radio" id="q13c" name="q13" value="c">
  <label for="q13c">85</label><br>
  <input type="radio" id="q13d" name="q13" value="d">
  <label for="q13d">106</label><br>
</div>  

<div style="background-color:lightgreen">
  <p>q14:15mangoes-17mangoes?</p><!--answer d -->

  <input type="radio" id="q14a" name="q14" value="a">
  <label for="q14a">2</label><br>
  <input type="radio" id="q14b" name="q14" value="b">
  <label for="q14b">3</label><br>
  <input type="radio" id="q14c" name="q14" value="c">
  <label for="q14c">1</label><br>
  <input type="radio" id="q14d" name="q14" value="d">
  <label for="q14d">NOT POSSIBLE</label><br>
</div>

<div style="background-color:lightblue">
  <p>q15:64/8?</p><!--answer c -->

  <input type="radio" id="q15a" name="q15" value="a">
  <label for="q15a">7</label><br>
  <input type="radio" id="q15b" name="q15" value="b">
  <label for="q15b">6</label><br>
  <input type="radio" id="q15c" name="q15" value="c">
  <label for="q15c">8</label><br>
  <input type="radio" id="q15d" name="q15" value="d">
  <label for="q15d">9</label><br>
  <br> 
</div>

<div style="background-color:lightgreen">
  <p>q16:3X7?</p><!--answer c -->

  <input type="radio" id="q16a" name="q16" value="a">
  <label for="q16a">18</label><br>
  <input type="radio" id="q16b" name="q16" value="b">
  <label for="q16b">21</label><br>
  <input type="radio" id="q16c" name="q16" value="c">
  <label for="q16c">24</label><br>
  <input type="radio" id="q16d" name="q16" value="d">
  <label for="q16d">15</label><br>
</div>

<br>
  <input type="submit" value="Submit">
</form>

</body>
</html>

PROJECT M.A.P/Project/map/templates/map/register.html
{% extends "map/base.html" %}
{% block content %}
  <form action="{% url 'map:add_student'  %}" method="POST">  //pending
    {% csrf_token %}
    <table align="center">
      <tr>
        <td>Name :</td>
        <td><input type="text" name="name" required></td>
      </tr>
      <tr>
        <td>Roll :</td>
        <td><input type="text" name="roll" required></td>
      </tr>
      <tr>
      </tr>
      <tr>
        <td><input type="submit" value="Submit"></td>
      </tr>
    </table>
  </form>
{% endblock content %}

PROJECT M.A.P/Project/map/templates/map/untitled_code.html
{% extends "map/base.html" %}
{% block content %}
    <p>WELCOME HOME</p>
    <article class="media content-section">
    	<div class="media-body">
    		<div class="article-metadata">
    			<a class="mr-2" href="#">{{ object }} </a>
    			<small class="text-muted">{{ object.start_date|date:"F d, Y"}}</small>
    		</div>
    		<h2 class="article-title">{{ object.start }}</h2>
    		<p class="article-content"> {{ object.description }} </p>
    	</div>
    </article>
{% endblock content %}