PROJECT M.A.P/Mounika/Mounika/urls.py
from django.contrib import admin
from django.urls import path, include
from mouni import views
from user import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('mouni.urls')),
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name = 'user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'user/logout.html'), name='logout'),

]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PROJECT M.A.P/Mounika/mouni/urls.py
from django.urls import path, include
from mouni import views
from mouni.views import (
	ExamListView,
	ExamDetailView, 
	MessageCreateView, 
	MessageUpdateView, 
	MessageDeleteView, 
	MessageDetailView
	)
from django.contrib.auth.decorators import login_required

app_name = 'mouni'

urlpatterns = [
    path('', ExamListView.as_view(), name='exam-list'),
    path("exam/<int:pk>/", login_required(ExamDetailView.as_view()), name="exam-detail"),
    path("create_exam/", views.create_exam, name="create-exam"),
    path('message/<int:pk>/detail/', login_required(MessageDetailView.as_view()), name='msg-detail'),
    path("message/", login_required(MessageCreateView.as_view()), name='msg'),
    path("message/<int:pk>/update/", MessageUpdateView.as_view(), name='msg-update'),
    path("message/<int:pk>/delete/", MessageDeleteView.as_view(), name='msg-delete'),
    path("display_results/", views.display_results, name="display-results"),
]

PROJECT M.A.P/Mounika/mouni/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from random import shuffle
import random

class Exam(models.Model):
	skillType = models.CharField(max_length = 20)
	subject = models.CharField(max_length = 20)
	start = models.DateTimeField(default = timezone.now)
	teacher = models.CharField(max_length = 20)

	def __str__(self):
		return self.skillType


class Question(models.Model):
	question = models.TextField()
	ans = models.CharField(max_length = 20)
	op2 = models.CharField(max_length = 20)
	op3 = models.CharField(max_length = 20)
	op4 = models.CharField(max_length = 20)
	exam = models.ForeignKey(Exam, on_delete = models.CASCADE)
	skill = models.CharField(max_length = 20)
	
	def __str__(self):
		return self.question

	def get_fields(self):
		#fields = [(field.name, field.value_to_string(self)) for field in Question._meta.fields[2:-2]]
		fields = [field.value_to_string(self) for field in Question._meta.fields[2:-2]]
		shuffle(fields)
		return fields

class Message(models.Model):
	title = models.CharField(max_length = 30)
	msg = models.TextField()
	student = models.ForeignKey(User, on_delete = models.DO_NOTHING)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
	 	#return reverse('msg-detail', kwargs={'pk':self.pk})
	 	return reverse('mouni:msg-detail', kwargs={'pk':self.pk}) #called on creation of new message

	def get_fields(self):
		fields = [(field.name, field.value_to_string(self)) for field in Message._meta.fields]
		shuffle(fields)
		return fields


class ResultPerExam(models.Model):
	student = models.ForeignKey(User, on_delete = models.DO_NOTHING)
	exam = models.ForeignKey(Exam, on_delete = models.DO_NOTHING)
	marks = models.PositiveIntegerField(editable = False)
	que_pick_ans = models.TextField() #just storing queid:0 or 1 #modify it to store question_id : chosen_option_number : correct_option_number
	seed = models.PositiveIntegerField(editable = False)

PROJECT M.A.P/Mounika/mouni/forms.py
from django import forms
from django.forms import (formset_factory, modelformset_factory)
from .models import Exam, Question

QuestionFormset = modelformset_factory(
    Question,
    fields=('question', 'ans', 'op2', 'op3', 'op4'),
    extra=1,
    widgets={'question': forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter Question here'
        }),
    'ans': forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter answer here'
        }),
    'op2': forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter option2 here'
        }),
    'op3': forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter option3 here'
        }),
    'op4': forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter option4 here'
        }),
    }
)

class ExamModelForm(forms.ModelForm):
    class Meta:
        model = Exam
        fields = '__all__'
        readonly_fields = ['teacher']
        widgets = {
            'teacher': forms.TextInput(attrs={'readonly':'readonly'})
        }

PROJECT M.A.P/Mounika/mouni/views.py
from django.shortcuts import render, redirect
from .models import (
    Exam, 
    Message, 
    Question,
    ResultPerExam,
)
from django.views.generic import (
    ListView,
    DetailView, 
    CreateView, 
    UpdateView,
    DeleteView
)
from django.http import HttpResponseRedirect, HttpResponse
from .forms import ExamModelForm, QuestionFormset
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
import csv
import random



class ExamListView(ListView):
    model = Exam
    template_name = 'mouni/home.html'
    context_object_name = 'exams'
    ordering = ['start'] 	



class ExamDetailView(LoginRequiredMixin, DetailView):
    model = Exam #context_object_name = 'exam'
    ordering = ['-start']

    # def __init__(self, *args, **kwargs):
    #     super(ExamDetailView, self).__init__(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ExamDetailView, self).get_context_data(**kwargs)
        try:
            r = ResultPerExam.objects.get(student_id = self.request.user.id, exam_id = self.kwargs[self.pk_url_kwarg])
            seed = r.seed
            print("seed read from ResultPerExam is ", seed)
            random.seed(seed)
            print("student already writen exam with seed = ", seed)
            context["has_written"] = True
            op_list = {}
            print(r.que_pick_ans)
            for _ in r.que_pick_ans.strip().split(","):
                print("_", _)
                qid, op_num, is_correct = [int(t) for t in _.strip().split(":")]
                print(qid, op_num)
                op_list[qid] = op_num
            context["op_list"] = op_list
        except ResultPerExam.DoesNotExist:
            context["has_written"] = False
            seed = random.randint(1, 100)
            random.seed(seed)
            context["seed"] = seed
            print("student now writing the exam with seed = ", seed)
        return context

    def post(self, request, *args, **kwargs):
        eid = request.POST['exam']
        seed = request.POST.get("seed")
        exam = Exam.objects.get(id = eid)
        res = exam.subject + " " + exam.skillType + " exam done!"
        res += "\n"
        res += "<h1>You have scored "
        score = 0
        print(exam.subject, exam.skillType)
        result = ResultPerExam()
        result.student_id = request.user.id
        result.exam_id = eid
        result.que_pick_ans = ""
        for q in exam.question_set.all():
            print(q, q.ans, request.POST.get(str(q.id)))
            op, op_num = request.POST.get(str(q.id)).split("+")
            if q.ans == op:
                score += 1
                result.que_pick_ans += str(q.id) + ":" + op_num + ":1,"
            else:
                result.que_pick_ans += str(q.id) + ":" + op_num + ":0,"
        result.que_pick_ans = result.que_pick_ans.rstrip(",")
        result.marks = score
        print("saving seed = ", seed)
        result.seed = seed
        result.save()
        res += str(score) + "</h1>"
        return HttpResponse(res, content_type="text/html")


@login_required
def display_results(request):
    if request.method == 'GET':
        student_id = request.user.id
        context = {
            'results' : ResultPerExam.objects.filter(student_id = student_id)
        }
        return render(request, 'mouni/display-results.html', context)
        


@login_required
@permission_required('mouni.add_exam', raise_exception=True)
def create_exam(request):
    template_name = 'mouni/create_exam.html'
    if request.method == 'GET':
        examform = ExamModelForm(request.GET or None, initial = {'teacher': request.user.username})
        examform.teacher = request.user.username
        formset = QuestionFormset(queryset=Question.objects.none())
    elif request.method == 'POST':
        examform = ExamModelForm(request.POST)
        formset = QuestionFormset(request.POST)
        if examform.is_valid() and formset.is_valid():
            # first save this exam, as its reference will be used in `Question`
            examform.teacher = request.user.username
            exam = examform.save()
            for form in formset:
                # so that `question` instance can be attached.
                question = form.save(commit=False)
                question.exam = exam 
                question.save()
            return redirect("mouni:exam-list")
    return render(request, template_name, {
        'examform': examform,
        'formset': formset,
    })

class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message

class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    fields = ['title', 'msg']

    def form_valid(self, form):
        form.instance.student = self.request.user
        return super().form_valid(form)

class MessageUpdateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Message
    fields = ['title', 'msg']

    def form_valid(self, form):
        form.instance.student = self.request.user
        return super().form_valid(form)

    def test_func(self):
        msg = self.get_object()
        if self.request.user == msg.student:
            return True
        return False

class MessageDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Message
    success_url = '/'
    
    def test_func(self):
        msg = self.get_object()
        if self.request.user == msg.student:
            return True
        return False

PROJECT M.A.P/Mounika/mouni/templates/mouni/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'mouni/main.css' %}">
    {% block custom_css %}{% endblock %}
    <title>Mounika Application</title>
</head>

<body>
    <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="/">Project M.A.P</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{% url 'mouni:exam-list' %}">Home</a>  <!-- no hardcoded links -->
            <a class="nav-item nav-link" href="#">About</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
              {% if user.is_authenticated %}
                   {% if perms.mouni.add_exam %}
                   <a class="nav-item nav-link" href="{% url 'mouni:create-exam' %}">New Exam</a>
                   {% endif %}
                   <a class="nav-item nav-link" href="{% url 'mouni:display-results' %}">Marks</a>
                  <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                  <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
              {% else %}
            <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
            <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
              {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>

    <div class="container">
        <div class="row spacer"></div>
        <div class="row offset-2">
            <div class="col-12">
                {% block container %}
                {% endblock %}
            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    {% block custom_js %}{% endblock %}
</body>
</html>

PROJECT M.A.P/Mounika/mouni/templates/mouni/create_exam.html
{% extends "mouni/base.html" %}

{% block container %}
{% if heading %}
<h3>{{heading}}</h3>
{% endif %}
<form class="form-horizontal" method="POST" action="">
    {% csrf_token %}
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class = "alert alert-danger">
                    <strong> {{ error|escape }} </strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class = "alert alert-danger">
                    <strong> {{ error|escape }} </strong>
            </div>
        {% endfor %}
    {% endif %}
<div class="row spacer">
<div class="col-2">
    <label>{{examform.subject.label}}</label>
</div>
<div class="col-4">
    <div class="input-group">
        {{examform.subject}}
    </div>
</div>
</div>
<div class="row spacer">
<div class="col-2">
    <label>{{examform.skillType.label}}</label>
</div>
<div class="col-4">
    <div class="input-group">
        {{examform.skillType}}
    </div>
</div>
</div>
<div class="row spacer">
<div class="col-2">
    <label>{{examform.teacher.label}}</label>
</div>
<div class="col-4">
    <div class="input-group" >
        {{examform.teacher}}
    </div>
</div>
</div>
<div class="row spacer">
<div class="col-2">
    <label>{{examform.start.label}}</label>
</div>
<div class="col-4">
    <div class="input-group">
        {{examform.start}}
    </div>
</div>
</div>
{{ formset.management_form }}
{% for form in formset %}
<div class="row form-row spacer">
    <div class="col-2">
        <label>{{form.question.label}}</label>
    </div>
    <div class="col-4">
        <div class="input-group">
            {{form.question}}
        </div>
        <div class="input-group">
            {{form.ans}}
        </div>
        <div class="input-group">
            {{form.op2}}
        </div>
        <div class="input-group">
            {{form.op3}}
        </div>
        <div class="input-group">
            {{form.op4}}
        </div>
    </div>
    <div class="input-group-append">
                <button class="btn btn-success add-form-row">+</button>
    </div>
</div>
{% endfor %}
<div class="row spacer">
    <div class="col-4 offset-2">
        <button type="submit" class="btn btn-block btn-primary">Create</button>
    </div>
</div>
</form>
{% endblock %}

{% block custom_js %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script type="text/javascript">
function updateElementIndex(el, prefix, ndx) {
    var id_regex = new RegExp('(' + prefix + '-\\d+)');
    var replacement = prefix + '-' + ndx;
    if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
    if (el.id) el.id = el.id.replace(id_regex, replacement);
    if (el.name) el.name = el.name.replace(id_regex, replacement);
}
function cloneMore(selector, prefix) {
    var newElement = $(selector).clone(true);
    var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
    newElement.find(':input:not([type=button]):not([type=submit]):not([type=reset])').each(function() {
        var name = $(this).attr('name')
        if(name) {
            name = name.replace('-' + (total-1) + '-', '-' + total + '-');
            var id = 'id_' + name;
            $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
        }
    });
    newElement.find('label').each(function() {
        var forValue = $(this).attr('for');
        if (forValue) {
          forValue = forValue.replace('-' + (total-1) + '-', '-' + total + '-');
          $(this).attr({'for': forValue});
        }
    });
    total++;
    $('#id_' + prefix + '-TOTAL_FORMS').val(total);
    $(selector).after(newElement);
    var conditionRow = $('.form-row:not(:last)');
    conditionRow.find('.btn.add-form-row')
    .removeClass('btn-success').addClass('btn-danger')
    .removeClass('add-form-row').addClass('remove-form-row')
    .html('-');
    return false;
}
function deleteForm(prefix, btn) {
    var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
    if (total > 1){
        btn.closest('.form-row').remove();
        var forms = $('.form-row');
        $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
        for (var i=0, formCount=forms.length; i<formCount; i++) {
            $(forms.get(i)).find(':input').each(function() {
                updateElementIndex(this, prefix, i);
            });
        }
    }
    return false;
}
$(document).on('click', '.add-form-row', function(e){
    e.preventDefault();
    cloneMore('.form-row:last', 'form');
    return false;
});
$(document).on('click', '.remove-form-row', function(e){
    e.preventDefault();
    deleteForm('form', $(this));
    return false;
});

</script>
{% endblock %}

PROJECT M.A.P/Mounika/mouni/templates/mouni/display-results.html
{% extends "mouni/base.html" %}
{% load static %}
{% block custom_css %}
 <link rel="stylesheet" href="{% static "mouni/results.css" %}" type="text/css" />
{% endblock %}
{% block container %}
<table id="results">
  <tr>
    <th>Subject</th>
    <th>Skill</th>
    <th>Marks</th>
  </tr>
  {% for result in results %}
      <tr>
      	<td>{{ result.exam.subject }} </td>
      	<td>{{ result.exam.skillType }}</td>
      	<td>{{ result.marks }}</td>
      </tr>
  {% endfor %}
</table>
{% endblock container %}

PROJECT M.A.P/Mounika/mouni/templates/mouni/exam_detail.html
{% extends "mouni/base.html" %}
{% load shuffle %}
{% block container %}
<form method=POST %}">
    {% csrf_token %}
     <div style="background-color:lightgreen">
        <h1>
            {% if has_written %}
                You have already written the exam
            {% else %}
                CHOOSE THE CORRECT ANSWER
            {% endif %}
        </h1>
    </div>
    {% if object.teacher == user.username %}
        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="#">Update</a>
         <a class="btn btn-danger btn-sm mt-1 mb-1" href="#">Delete</a>
    {% endif %}
    <input type="hidden" name="exam" value={{ object.id }}>
    <input type="hidden" name="seed" value= "{{ seed }}">
    {% for question in object.question_set.all|shuffle %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    {{ forloop.counter }} &emsp; {{ question }}
                    {% comment %}
                    <!-- <small class="text-muted">{{ exam.start_date|date:"F d, Y"}}</small> -->
                    {% endcomment %}
                </div>
                    {% for value in question.get_fields %}
                        {% if has_written %}
                            {% ifequal op_list|get_item:question.id forloop.counter %}
                                {% with checked="True" %}
                                    {% ifequal question.ans value %}
                                        <div style="background-color:lightgreen">
                                            <input type="radio", disabled=True checked={{checked}}>
                                            <label > {{ value }} </label> <br>
                                        </div>
                                    {% else %}
                                        <div style="background-color:lightsalmon">
                                            <input type="radio", disabled=True checked={{checked}}>
                                            <label > {{ value }} </label> <br>
                                        </div>
                                    {% endifequal %}
                                {% endwith %}
                            {% else %}
                                {% ifequal question.ans value %}
                                    <div style="background-color:lightgreen">
                                        <input type="radio", disabled=True>
                                        <label > {{ value }} </label> <br>
                                    </div>
                                {% else %}
                                    <div>
                                        <input type="radio", disabled=True>
                                        <label > {{ value }} </label> <br>
                                    </div>
                                {% endifequal %}
                            {% endifequal %}
                        {% else %}
                        <input type="radio" id="{{ forloop.parentloop.counter }}{{ forloop.counter }}" name="{{ question.id }}" value="{{ value }}+{{ forloop.counter }}" required="True">
                        <label for="{{ forloop.parentloop.counter }}{{ forloop.counter }}" > {{ value }} </label> <br>
                        {% endif %}
                    {% endfor %}
            </div>
        </article>
    {% endfor %}
    {% if has_written %}
    {% else %}
    <div class="row spacer">
        <div class="col-4 offset-2">
            <button type="submit" class="btn btn-block btn-primary">Submit</button>
        </div>
    </div>
    {% endif %}
</form>
{% endblock container %}

PROJECT M.A.P/Mounika/mouni/templates/mouni/home.html
{% extends "mouni/base.html" %}
{% load static %}
{% block container %}
    <p>WELCOME HOME</p>
    {% for exam in exams %}
        <article class="media content-section">
        	<div class="media-body">
        		<div class="article-metadata">
        			<a class="mr-2" href="{% url 'mouni:exam-detail' exam.pk %}">{{ exam.skillType }} </a>
                    <small class="text-muted">Subject : {{ exam.subject}}</small> 
        			<small class="text-muted">Exam date : {{ exam.start}}</small> 
                    <small class="text-muted">teacher: {{ exam.teacher }}</small>
        		</div>
        		{% comment %}
        		<!-- <h2><a class="article-title" href="#">{{ exam.start }}</a></h2>
        		<p class="article-content"> {{ exam.description }} </p> -->
        		{% endcomment %}
        	</div>
        </article>
    {% endfor %}
{% endblock container %}

PROJECT M.A.P/Mounika/mouni/templates/mouni/message_confirm_delete.html
{% extends "mouni/base.html" %}
{% block container %}
    <div class="content-section">
    	<form method = "POST">
    		{% csrf_token %}
    		<fieldset class ="form-group">
    			<legend class="border-bottom mb-4">
                    Delete Message
    			</legend>
                <h2> Delete "{{ object.title }}" ?</h2>
     		</fieldset>
    		<div class="form-group">
    			<button class="btn btn-outline-danger" type="submit">Delete</button>
                <a class="btn btn-outline-secondary" href ="{% url 'mouni:msg-detail' object.id %}" >Cancel</a>
    		</div>
    	</form>
    </div>
{% endblock container %}

PROJECT M.A.P/Mounika/mouni/templates/mouni/message_detail.html
{% extends "mouni/base.html" %}
{% block container %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="#">{{ object.student }}</a>
                {% if object.student == user.username %}
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'mouni:msg-update' object.id%}">Update</a>
                        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'mouni:msg-delete' object.id %}">Delete</a>
                    </div>
                {% endif %}
                <div>
                    <h2 class="article-title">{{ object.title }}</h2>
                    <p class="article-content">{{ object.msg }}</p>
                    {% for name, value in object.get_fields %}
                        <h2 class="article-title">{{ name }}</h2>
                        <p class="article-content">{{ value }}</p>
                    {% endfor %}
                </div>
            </div>            
        </div>
    </article> 
{% endblock container %}

PROJECT M.A.P/Mounika/mouni/templates/mouni/message_form.html
{% extends "mouni/base.html" %}
{% load crispy_forms_tags %}
{% block container %}
    <div class="content-section">
    	<form method = "POST">
    		{% csrf_token %}
    		<fieldset class ="form-group">
    			<legend class="border-bottom mb-4">
                    Message Teacher
    			</legend>
    			{{ form|crispy }}
    		</fieldset>
    		<div class="form-group">
    			<button class="btn btn-outline-info" type="submit">Send</button>
    		</div>
    	</form>
    </div>
{% endblock container %}

PROJECT M.A.P/Mounika/mouni/templates/mouni/result.html
<h1>
	 write page to display results
</h1>